/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neub.carParkingManagementSystem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.print.Printer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ss
 */
public class ReceptClass extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form ReceptClass
     */
    String text = "";

    public ReceptClass(String name, String license, String placeOrPrice, String time, String date) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
       // nameLevel.setText("Name : " + name);

        text += "Name : " + name + "\n\n" + "License No : " + license + "\n\n" + placeOrPrice + "\n\n       Time : " + time + "\n       Date : " + date;
        printTextArea.setText(text);
        printButton.addActionListener(this);

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        callStartPage();
    }

    void callStartPage() {
        try {

            Boolean printcalar = printTextArea.print();
            if (printcalar) {
                JOptionPane.showMessageDialog(null, "Done Print ....");
            } else {
                //JOptionPane.showMessageDialog(null, "Printing ....");
            }
        } catch (PrinterException ex) {
            Logger.getLogger(ReceptClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        StartPage object = new StartPage();
        object.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        printButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        printTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));

        printButton.setBackground(new java.awt.Color(102, 255, 51));
        printButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        printButton.setForeground(new java.awt.Color(0, 0, 255));
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.jpg"))); // NOI18N

        printTextArea.setBackground(new java.awt.Color(153, 153, 0));
        printTextArea.setColumns(20);
        printTextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        printTextArea.setForeground(new java.awt.Color(51, 0, 255));
        printTextArea.setRows(5);
        jScrollPane1.setViewportView(printTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JTextArea printTextArea;
    // End of variables declaration//GEN-END:variables

}
