/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neub.carParkingManagementSystem;

import java.util.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.Action;
import javax.swing.JOptionPane;

/**
 *
 * @author ss
 */
public class StartPage extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
        //placeAdd();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        registrationCarButton.addActionListener(this);
        registrationClientButton.addActionListener(this);
        //viewCarButton.addActionListener(this);
        viewClientButton1.addActionListener(this);
        searchCarButton.addActionListener(this);
        exitMenu.addActionListener(this);
        aboutMenu.addActionListener(this);
        viewCar.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == registrationClientButton) {
            callRegistrationClientClass();
        } else if (e.getSource() == searchCarButton) {
            callSearchCarClass();
        } else if (e.getSource() == registrationCarButton) {
            callsearchOwnerClass();
        } else if (e.getSource() == viewClientButton1) {
            callView_ClientClass();
        }
        if (e.getSource() == exitMenu) {
            exitMethod();
        }
        if (e.getSource() == aboutMenu) {
            aboutMethod();
        }
        if (e.getSource() == viewCar) {
            callViewCarMethod();
        }
    }

    public void callViewCarMethod() {
        setVisible(false);
        View_Car obj = new View_Car();
        obj.setVisible(true);
    }

    public void exitMethod() {
        System.exit(0);
    }

    public void aboutMethod() {
        JOptionPane.showMessageDialog(null, "This is a project of car parking management system developed by Shuvro and Shameem");
    }

    void callView_ClientClass() {
        this.setVisible(false);
        View_Client object = new View_Client();
        object.setVisible(true);
    }

    public void placeAdd() {

        //String query = "Select * FROM registrationtable";
        int i = 1;
        String s = "" + i, s1 = "0";
        while (i < 300) {

            s = "" + i++;

            try {
                Connector_DataBase ob1 = new Connector_DataBase();
                String query = "INSERT INTO placetable " + "VALUES ('" + s + "', '" + s1 + "')";
                ob1.statement.executeUpdate(query);
                ob1.connection.close();
            } catch (SQLException ev) {
                ev.printStackTrace();
            }

        }
    }

    public void callRegistrationClientClass() {
        setVisible(false);
        RegistrationClient object = new RegistrationClient();
        object.setVisible(true);

    }

    public void callSearchCarClass() {
        setVisible(false);
        SearchCar object = new SearchCar();
        object.setVisible(true);

    }

    public void callsearchOwnerClass() {
        setVisible(false);
        SearchOwner object = new SearchOwner();
        object.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registrationClientButton = new javax.swing.JButton();
        registrationCarButton = new javax.swing.JButton();
        viewCar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchCarButton = new javax.swing.JButton();
        viewClientButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrationClientButton.setBackground(new java.awt.Color(51, 102, 255));
        registrationClientButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registrationClientButton.setForeground(new java.awt.Color(255, 255, 255));
        registrationClientButton.setText("Registration Client");
        registrationClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationClientButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registrationClientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 228, 244, 37));

        registrationCarButton.setBackground(new java.awt.Color(51, 102, 255));
        registrationCarButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registrationCarButton.setForeground(new java.awt.Color(255, 255, 255));
        registrationCarButton.setText("Registration Car");
        jPanel1.add(registrationCarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 244, 36));

        viewCar.setBackground(new java.awt.Color(51, 102, 255));
        viewCar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewCar.setForeground(new java.awt.Color(255, 255, 255));
        viewCar.setText("View Car");
        jPanel1.add(viewCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 244, 33));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/635519357112085465-1376219653_parking.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        searchCarButton.setBackground(new java.awt.Color(51, 102, 255));
        searchCarButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchCarButton.setForeground(new java.awt.Color(255, 255, 255));
        searchCarButton.setText("Search Car");
        jPanel1.add(searchCarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 439, 244, 35));

        viewClientButton1.setBackground(new java.awt.Color(51, 102, 255));
        viewClientButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewClientButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewClientButton1.setText("View Client");
        jPanel1.add(viewClientButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 244, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2CB3EA0100000578-3247151-image-a-59_1443074256502.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 500, 260));

        jMenu1.setText("File");

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenu.setText("Exit");
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        helpMenu.setText("Help");

        aboutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenu.setText("About");
        helpMenu.add(aboutMenu);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrationClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationClientButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_registrationClientButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrationCarButton;
    private javax.swing.JButton registrationClientButton;
    private javax.swing.JButton searchCarButton;
    private javax.swing.JButton viewCar;
    private javax.swing.JButton viewClientButton1;
    // End of variables declaration//GEN-END:variables

}
